DjangoAjax/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.index, name='index'),
    path('post_params/', views.post_params, name = "post_params")
]

polls/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 


class SimParamsModel (models.Model):
    admin_stations = models.SmallIntegerField( null=False, validators=[MinValueValidator(1), MaxValueValidator(100)])
    admin_low = models.PositiveSmallIntegerField(null=False, validators=[MinValueValidator(1), MaxValueValidator(100)])
    admin_hi = models.PositiveSmallIntegerField(null=False, validators=[MinValueValidator(1), MaxValueValidator(100)])

    def __str__(self):
        return self.title
# Create your models here.

polls/forms.py
from .models import SimParamsModel
from django import forms

class SimParamsForm(forms.ModelForm):
    class Meta:
        model = SimParamsModel
        fields = ("__all__")

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from .models import SimParamsModel
from django.core import serializers
from .forms import SimParamsForm


def index(request):
  print('Hello')
  context ={}
  form = SimParamsForm
  context['form'] = form
  #return HttpResponse("Hello world. You're at the polls index.")
  return render(request, 'polls/index.html',context)
# Create your views here.


def post_params(request):
  print('from post_params')
  # request should be ajax and method should be POST.
  if request.is_ajax and request.method == "POST":
      # get the form data
      form = SimParamsForm(request.POST)
      # save the data and after fetch the object in instance
      if form.is_valid():
          
          instance = form.save()
          
          # serialize in new friend object in json
          ser_instance = serializers.serialize('json', [ instance, ])
          print(ser_instance)
          # send to client side.
          return JsonResponse({"instance": ser_instance}, status=200)
      else:
          # some form errors occured.
          return JsonResponse({"error": form.errors}, status=400)

  # some error occured
  return JsonResponse({"error": ""}, status=400)

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Hello World {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   
    {% block style %}
     
  
    {% endblock style %}
</head>

<body>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>



    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

polls/templates/polls/index.html
<head>

</head>

{% extends "polls/base.html" %}

{% block javascript %}
<script>
  $( document ).ready(function() {
    console.log( "ready!" );
    $("#id_admin_stations").change(function(){
      console.log("hello")
    })

    $("params_form").submit(function(){
      console.log("Button")
      e.preventDefault();
        // serialize the data for sending the form data.
      var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
          type:'POST',
          url:"{% url 'post_params' %}",
          data:serializedData,
          success:function(res){
            console.log(JSON.parse(res))
          },
          error:function(err){
            console.log({err:err})
          }
        })
    })

});
// $(document)
// $("id_admin_tau").change(function(e){
//   console.log($(this).val())
  // e.preventDefaults();
  // var serializedData = $(this).serialize()
  // console.log(serializedData)

</script>
{% endblock javascript%}



{% block content %}
<!-- <form method = "post">
  {% csrf_token%}
  {{form.as_p}}
  <input  id = "btn" type="submit" value ="post_params"></button>
</form> -->
 <div class="container-fluid">
    <form method = "post" id="params-form" action = "post_params/">
        <div class="row">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-4">
                <label class="col-12">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input  type="submit" class="btn btn-primary" value="Create Friend" />
        </div>
    <form>
</div> 
{% endblock content %}